[package]
name = "round-robin-pairing"
version = "0.1.0"
authors = ["Mehmet Sefa Balık <mehmetsefa2644@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"

[dev-dependencies]
fake = "2.2"